Change validation to if from && chain

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -33,8 +33,14 @@ runs:
   - shell: bash
     run: |
       # validation
-      [ "${{ inputs.api-key }}"  = "" -a "${{ inputs.bearer-token }}"  = "" ] && echo "Any of api-key or bearer-token must be provided" && exit 1
-      [ "${{ inputs.api-key }}" != "" -a "${{ inputs.bearer-token }}" != "" ] && echo "Both api-key and bearer-token cannot be used together" && exit 1
+      if [ "${{ inputs.api-key }}"  = "" -a "${{ inputs.bearer-token }}"  = "" ]; then
+        echo "Any of api-key or bearer-token must be provided"
+        exit 1
+      fi
+      if [ "${{ inputs.api-key }}" != "" -a "${{ inputs.bearer-token }}" != "" ]; then
+        echo "Both api-key and bearer-token cannot be used together"
+        exit 1
+      fi
 
   - shell: bash
     run: |
