Update validation

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -32,7 +32,9 @@ runs:
   steps:
   - shell: bash
     run: |
-      [ ${{ inputs.api-key }} != "" -a ${{ inputs.bearer-token }} != "" ] && echo "api-key and bearer-token cannot be used together" && exit 1
+      # validation
+      [ ${{ inputs.api-key }} = "" -a ${{ inputs.bearer-token }} = "" ] && echo "Any of api-key or bearer-token must be provided" && exit 1
+      [ ${{ inputs.api-key }} != "" -a ${{ inputs.bearer-token }} != "" ] && echo "Both api-key and bearer-token cannot be used together" && exit 1
 
   - shell: bash
     run: |
